### ISSUE TITLE
AT4DX Questions 

### ISSUE THREAD

**Issue by semenoar** [apex-enterprise-patterns/at4dx#39]
Hello @ImJohnMDaniel & @stohn777,

I am not sure if this is the appropriate communication channel to ask a few questions, but here I go.

1. First question, to break business processes into Criteria's and Actions, does not only help organize the business logic into readable logical blocks but also creates a great layer within the metadata that allows our admins, architects, & business users get a better understanding of what is going on within the code. But from what I see with the approach taken in at4dx with criteria/action it is not friendly in terms of Execution Governors and Limits. For example, each criteria class might need to qualify records by soql'ing related data but also it might need to use this soql'ed data within the action class. With the current implementation of at4dx it will require you to re-soql the data which adds to the allowed transaction limits. Now if you have multiple processes for a particular SObject Domain that might add pretty quickly and Governors/Limits might become a problem. Have you considered this problem and how it might be solved? Potentially making the criteria class instances available to the actions. Or something more complex that allows bulkification of a transaction, by querying all the records required to complete a transaction within a domain for all criteria's & actions. 

2. Also the idea to execute bindings based on a DomainMethodToken it being either the TriggerOperation or set of specific process bindings to run for all trigger operations is great. I was wondering, if based on a particular SObject domain that has multiple processes defined by a RecordType and the requirement is to execute a set of bindings for a particular Trigger Operation and Record Type how would you accomplish this? I am assuming you are able to define your process bindings using the DomainMethodToken__c and then within each criteria class further qualify the records by the Trigger Operation. But this creates a gap when reviewing the Metadata Process Bindings records. I was just wondering if this is a valid scenario and if you have thought of making the Process Bindings be more specific for a process by using a combination of DomainMethodToken__c & TriggerOperation__c?

3. As part of the at4dx model, I was wondering if it's wrong to think that the Action Class might need access to Existing Records as part of an update operation? and if passing the Existing Records to the Action Class is not advisable in this model. 

Thanks in advance.

**Comment by ImJohnMDaniel** [comment]
G'day @semenoar -- Thanks for reaching out.

Regarding your questions and comments:

- re: AT4DX Criteria and Actions "...not friendly in terms of Execution Governors and Limits" -- You point is certainly valid.  When the framework was originally created, we did think about a potential to facilitate the ability to cache records in the `DomainProcessCoordinator` class, but at the time we only had some edge cases that could take advantage of that feature and decided to not pursue it.  We would welcome you thoughts (in a separate feature request issue) about how you would like to see it handled.  Our own analysis suggests that we would probably need some sort of 'lazy loading' / identify map because, in theory, you could have two criteria and an action in one domain process and the first criteria could cache the records and the second criteria and subsequent action could use them.  But what do you do when the action is used in a totally different domain process and it doesn't have that first criteria taking care of the loading of the records.  So, there are definitely pros and cons to this feature.  Again, we would welcome your thoughts about how this should work.

- re: DomainMethodToken vs TriggerOperation -- So the thought here is that it is an "either/or" feature.  You will specify the TriggerOperation approach or the DomainMethodToken approach.  The DomainMethodToken option is for use cases where you are wanting to call an orchestrated domain process from a Service tier class or maybe another Domain class.  In theory could call another Domain that is part of another package and simply wrap the call in a try/catch thus allowing for the functionality to be called, if the code were present in the org, and it still be loosely coupled.

- re: Action Class might need access to Existing Records as part of an update operation -- That is a great suggestion.  @stohn777 and I were reviewing how this would be accomplished and we have a viable way to make it happen.  Look for an update to the AT4DX framework within the next few days with that feature.

Let us know if you have any further questions.  Cheers!

**Comment by ImJohnMDaniel** [comment]
@semenoar -- regarding your suggestion of Action Class needing access to Existing Records, that change is now merged into the codebase

**Comment by vyasp** [comment]
@ImJohnMDaniel -- Great Addition, love it! 👍  
Two Questions while I was trying to get my head around it,
1)Should interface IDomainProcessActionWithExistingRecs be implemented directly with the new Action class as a selective feature? or should we look to implement it in the DomainProcessAbstractAction so that it is available to all action class extending it?
2) This more on the cosmetic side, should IDomainProcessActionWithExistingRecs be located under "framework-domain-process-injection" instead of "framework-application-factory"

**Comment by ImJohnMDaniel** [comment]
@vyasp -- Implement `IDomainProcessActionWithExistingRecs` selectively as needed.  It would be put in the `DomainProcessAbstractAction` class.  

Regarding the directory location -- Good catch.  correcting now.

Cheers!
