### ISSUE TITLE
Question: Is the Event_Name field required for AT4DX_Message__e and AT4DX_Immediate_Message__e?

### ISSUE THREAD

**Issue by chazwatkins** [apex-enterprise-patterns/at4dx#63]
`Platform Event - Subscription` records allow Matcher Rules without `Event Name`.  However, the `Event Name` field is listed as required = true on `AT4DX_Message__e` and `AT4DX_Immediate_Message__e`.

Is it intentional to have `Event Name` set as required by default?

**Comment by ctchipps** [comment]
Yes, this is intentional. The idea is that your subscription can be "wider" than the scope of a single event. So you could write a subscription that just matches on the event bus without any regard for the name of the events being processed by that event bus. It is recommended that you provide every event with a meaningful name, even if you are using one of the wider subscription scopes. That way in the future if you ever need to "tighten" an event subscription, you aren't left in an awkward spot.
