### ISSUE TITLE
SelectorMethodInjectable return List<object>

### ISSUE THREAD

**Issue by sl-mickaellopes** [apex-enterprise-patterns/at4dx#93]
**Is your feature request related to a problem? Please describe.**
When writting selector with "group by" to SOQL, the query return a SObject "AggregateResult" type.
In test class it's not possible mock this selector because SObject "AggregateResult" it's readonly => [SOQL Aggregate Functions](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_SOQL_agg_fns.htm)

Ex : 
```Apex
public with sharing class MyCustomSelectorMethod extends AbstractSelectorMethodInjectable implements ISelectorMethodInjectable {
       public List<SObject> selectQuery() {

            MyCustomSelectorMethod.Parameters params = (MyCustomSelectorMethod.Parameters) getParameters();
            Set<Id> Ids = params.Ids;

             fflib_QueryFactory query = new fflib_QueryFactory(Contact.SObjectType)
                 .selectField(Contact.AccountId)
                 .selectField(Contact.CustomField)
                 .setCondition('AccountId IN :ids GROUP BY AccountId, CustomField);

            return Database.query(query.toSOQL());
       }
....
}
```

**Describe the solution you'd like**
I would like be able to inject methods that return `List<object>` and not only `List<SObject>`
Ex: 
```Apex
public with sharing class MyCustomSelectorMethod extends AbstractSelectorMethodInjectable implements ISelectorMethodInjectable {
       public List<object> selectQuery() 
       {
           ...
           List<SObject> result = Database.query(query.toSOQL());
           return this.convert(result);
       }
       private List<MyCustomResult> convert(List<SObject> objs)
       {
          -> convert AggregateResult[] To List<MyCustomResult>
          -> Return List<MyCustomResult>
       }
}
```

So I could transform in selector the SObjects aggregateResult to custom object class and return this custom object which are mockable

**Comment by ImJohnMDaniel** [comment]
@sl-mickaellopes -- We have reviewed the request and have decided not to pursue this enhancement at this time.

However, if the only reason for the enhancement is because the `AggregateResult` is read only and not mockable in a unit test, can I ask if you have tried to use the [ApexMocks `fflib_ApexMocksUtils.setReadOnlyFields(SObject, Type, Map<SObjectField, Object>)` method](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/master/sfdx-source/apex-mocks/main/classes/fflib_ApexMocksUtils.cls#L98)?  It provides a way to instantiate read only objects and preset their fields as well.  I, personally, have not tried it with `AggregateResult` but it is certainly worth a try.  If you have a question about its usage, feel free to open a question on the [ApexMocks repo](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/issues).

Cheers!

**Comment by sl-mickaellopes** [comment]
@ImJohnMDaniel Yes, i'm agree but it's not possible to have a method that return List<object> and not only List<SObject>
`public List<object> selectQuery() ` ?

With this return value we can mock the method "selectQuery"

**Comment by ImJohnMDaniel** [comment]
I appreciate the ask @sl-mickaellopes but we will be waiting for the release of the feature to natively mock AggregateResult.  Selector pattern methods should stay focused on `SObject` as the return value.  With that in mind, we don't want to introduce a feature that deviates from the premise only to support a feature that will eventually come from the platform.
